Core/Currency.Core/ViewModels/SubscriptionViewModel.cs
using GlobalNews.Models.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Currency.Core.ViewModels
{
    public class SubscriptionViewModel
    {
        public List<List<Author>> Authors { get; set; } = new List<List<Author>>();
        public List<List<Category>> Categories { get; set; } = new List<List<Category>>();

    }
}

Core/Currency.Core/Controllers/SubscriptionController.cs
using Currency.Core.ViewModels;
using GlobalNews.Data.Data;
using GlobalNews.Models.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Currency.Core.Controllers
{
    [Authorize]
    public class SubscriptionController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly DataManager _manager;
        private readonly UserManager<User> _userManager;

        public SubscriptionController(ApplicationDbContext context, DataManager manager, UserManager<User> userManager)
        {
            _context = context;
            _manager = manager;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            SubscriptionViewModel model = new SubscriptionViewModel();
            var user = await _userManager.GetUserAsync(User);
            model.Authors = await _context.Users
                .Where(x => x.Id == user.Id)
                .Select(x => x.Authors).ToListAsync();
            model.Categories = await _context.Users
                .Where(x => x.Id == user.Id)
                .Select(x => x.Categories).ToListAsync();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UnsubscribeCategory(int id)
        {
            var category = await _context.Categories
                .Include(x => x.Articles.Where(x => x.ArticleStatus == ArticleStatus.Published))
                .Include(x => x.Users)
                .FirstOrDefaultAsync(x => x.Id == id);
            var user = await _userManager.GetUserAsync(User);

            user.Categories.Remove(category);
            _context.Users.Update(user);
            await _context.SaveChangesAsync();

            SubscriptionViewModel model = new SubscriptionViewModel();

            model.Authors = await _context.Users
                .Where(x => x.Id == user.Id)
                .Select(x => x.Authors)
                .ToListAsync();
            model.Categories = await _context.Users
                .Where(x => x.Id == user.Id)
                .Select(x => x.Categories)
                .ToListAsync();
            return View("Index", model);
        }

        [HttpPost]
        public async Task<IActionResult> UnsubscribeAuthor(int id)
        {
            var author = await _context.Authors
                .Where(x => x.Articles.Any(x => x.ArticleStatus == ArticleStatus.Published))
                .Include(x => x.Articles)
                .Include(x => x.Users)
                .FirstOrDefaultAsync(x => x.Id == id);
            var user = await _userManager.GetUserAsync(User);

            user.Authors.Remove(author);
            _context.Users.Update(user);
            await _context.SaveChangesAsync();

            SubscriptionViewModel model = new SubscriptionViewModel();

            model.Authors = await _context.Users.Where(x => x.Id == user.Id).Select(x => x.Authors).ToListAsync();
            model.Categories = await _context.Users.Where(x => x.Id == user.Id).Select(x => x.Categories).ToListAsync();
            return View("Index", model);
        }
    }
}

Core/Currency.Core/Views/Subscription/Index.cshtml
@model SubscriptionViewModel
<div class="row">
    
    <div class="text-center fs-3">Авторы</div>
    @foreach (var mainAuthor in Model.Authors)
    {
        @foreach (var author in mainAuthor)
        {
            <div class="allcolor">
            </div>
            <div class="row align-items-center mycolor p-3 mycolor">
                <a asp-action="Author" asp-controller="Author" asp-route-id="@author.Id"
                   class="col-md-10">@author.FirstName @author.LastName</a>
                <form class="col-md-2" asp-action="UnsubscribeAuthor" asp-controller="Subscription">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group">
                        <input type="hidden" asp-for="@author.Id" name="id" />
                    </div>
                    <div >
                        <input class="btn btn-danger" type="submit" value="Отписаться" />
                    </div>
                </form>
            </div>
        }
    }
</div>



<div class="row">
    <div class="text-center fs-3">Категории</div>
    @foreach (var mainCategoties in Model.Categories)
    {
        @foreach (var category in mainCategoties)
        {
            <div class="allcolor">
            </div>
            <div class="row align-items-center mycolor p-3 mycolor">
                <a asp-action="Category" asp-controller="Category" asp-route-id="@category.Id"
                   class="col-md-10">@category.Name</a>
            <form class="col-md-2" asp-action="UnsubscribeCategory" asp-controller="Subscription">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <input type="hidden" asp-for="@category.Id" name="id" />
                </div>
                <div>
                    <input class="btn btn-danger" type="submit" value="Отписаться" />
                </div>
            </form>
            </div>
        }
    }
</div>